### DISCUSSION TITLE
got the same [custom_components.saj_esolar.sensor] return data NONE

### DISCUSSION THREAD

**Discussion by hwvvse** [djansen1987/SAJeSolar#24] [Q&A] [answered]
but i couldn't find any solution in the "solved" thread...

**Comment by djansen1987** [comment]
could you share some more information.

What type of device do you use, and please share your sensor setup (without username/password)

**Reply by hwvvse** [reply]
sure here it is
```yaml
sensor:
  - platform: saj_esolar
    username: myemail@asdasdasd
    password: secretpassword
    resources:
      - nowPower
      - runningState
      - todayElectricity
      - monthElectricity
      - yearElectricity
      - totalElectricity # Energy -> Solar production
      - todayGridIncome
      - income
      - lastUploadTime
      - totalPlantTreeNum
      - totalReduceCo2
      - todayAlarmNum
      - status
      - plantuid
      - currency
      - address
      - isOnline
      - peakPower
logger:
  default: info
  logs:
    custom_components.saj_esolar: debug
```

got two inverters Suntrio Plus 8K and Suntrio Plus 5K 
only pasted in this in configuration.yaml
