### DISCUSSION TITLE
peakPower is "unknown"

### DISCUSSION THREAD

**Discussion by tamasrell2** [djansen1987/SAJeSolar#56] [General]
Hi!

I have an R5-2.5K-S1-15 inverter. Since the last update (v1.4.3) the state of peakPower is "unknown".
NowPower and all other resources are working fine, updating normally.
My config is basically the copy of the readme:
```
  - platform: saj_esolar
    username: ----my email----
    password: -----my pw-----
    plant_id: 0
    resources:
      - nowPower
      - peakPower    
      - runningState
      - todayElectricity
etc...
```
Does peakPower work on your HA? Is it a problem on my side? 

Thanks!
Tamas
