### ISSUE TITLE
uitlezen SAJ converter

### ISSUE THREAD

**Issue by robbedoes14** [djansen1987/SAJeSolar#53]
Hoi,

Ik heb een R5-12K-T2 SAJ omvormer met Aio3 module (met een Ethernet connectie in mijn router). Op de eSolar Portal kan ik inloggen en alle log gegevens bekijken.

Is het mogelijk om dit te integreren in Home Assistant ? Mij is niet helemaal duidelijk of dit nu wel of niet mogelijk is met deze integratie in HA.

Alvast dank.

**Comment by djansen1987** [comment]
Hi Rob,

Het is mogelijk via de custom intergratie die ik hiervoor gemaakt heb. Let even op bij het installeren dat je niet kiest voor de beta versie wanneer je hem via Hacs installeerd. Wanneer je het handmatig doet, kies dan deze release: https://github.com/djansen1987/SAJeSolar/releases/tag/v1.3.1

Wanneer je geen batterij module of de SEC module in je meterkast heb komt je config er zo uit te zien:

```yaml
sensor:
  - platform: saj_esolar
    username: aa@bb.cc
    password: abcd1234
    plant_id: 0 # Default is 0. Typically ordered in the same way as they are listed in the eSolar app
    resources:
      - nowPower
      - runningState
      - todayElectricity
      - monthElectricity
      - yearElectricity
      - totalElectricity # Energy -> Solar production
      - todayGridIncome
      - income
      - lastUploadTime
      - totalPlantTreeNum
      - totalReduceCo2
      - todayAlarmNum
      - isAlarm # Yes / No
      - status
      - plantuid
      - currency
      - address
      - isOnline
      - peakPower
      - systemPower # Installed capacity
```
